# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ising_gibbs_sweep_ <- function(state, proba_beta) {
    .Call('_couplingsmontecarlo_ising_gibbs_sweep_', PACKAGE = 'couplingsmontecarlo', state, proba_beta)
}

